### ISSUE TITLE
Fix Pigeon

### ISSUE THREAD

**Issue by centiwati** [denbot/2024CompetitionSeason#29]
Pigeon doesn't seem to work; our robot moves in the wrong direction.

**Comment by Jnesselr** [comment]
Which direction should be considered the front of the robot? Currently the pigeon is zeroed on startup, right? Do your auto routines take into a account the different possible placements of the robot and how that affects the initial measured heading?

**Comment by centiwati** [comment]
We want the intake to be the front for the porpoises of autos.
