### ISSUE TITLE
Determine control system

### ISSUE THREAD

**Issue by Jnesselr** [denbot/2024CompetitionSeason#4]
We're using the [XboxController](https://first.wpi.edu/wpilib/allwpilib/docs/release/java/edu/wpi/first/wpilibj/XboxController.html) for our robot. We need to figure out what buttons do what.

**Comment by GucciBanana11** [comment]
Functions: 
- Drive
- Rotate
- Intake
- Shoot (amp and speaker)
- Climb (?)

All of the specific buttons are just suggestions and placeholders

Driving:
  Drive will be controlled by the left joystick, field oriented 
  Rotate (drive base) would be controlled by the right joystick

Intake:
  Intake could be controlled automatically, being a breakbeam sensor in front of the intake that senses when there is a note and automatically fire the motors to intake the note. It would also be nice if we could get the controller to vibrate as confirmation of a note. 

Shooting: 
  A - run motors and angle for amp shooting
  B - run motors and angle for bpeaker shooting
  A/B + RT - fire for amp/bpeaker. Once fired, the angle will return to the default. In case of not wanting to fire but have already started up the motors, the back (small button on the left of the Xbox button) would be used. This would likely be needed for going under the stage area. A vibrate confirmation would also be nice here. 

Climb: 
  We would want to do a combo for this, something like both triggers/both bumpers, so it is harder to do accidentally. 

Other ideas:
  Some sort of timer as a failsafe for trying to climb too early
  Technician controller would be used as manual failsafes, an example being if the automatic intake doesn't work, there is a manual option.

**Comment by GucciBanana11** [comment]
![IMG_20240127_121041485](https://github.com/Anglebotics/2024CompetitionSeason/assets/111261307/24f574c3-a802-421a-9583-7f71bafbb802)

**Comment by GucciBanana11** [comment]
Beautiful image credit goes to charlie
